{
  "records":{
     "data":[
        {
           "customGoldenRecord":{
              "auxId":"rec-00000000-aaa-0",
              "city":"Nairobi",
              "dob":"20171114",
              "familyName":"Onyango",
              "gender":"male",
              "givenName":"Endalekachew",
              "nationalId":"198804042874913",
              "phoneNumber":"091-749-4674",
              "sourceId":[
                 
              ],
              "uid":"0x5"
           },
           "mpiEntityList":[
              {
                 "entity":{
                    "auxId":"rec-00000000-aaa-0",
                    "city":"Nairobi",
                    "dob":"20171114",
                    "familyName":"Onyango",
                    "gender":"male",
                    "givenName":"Endalekachew",
                    "nationalId":"198804042874913",
                    "phoneNumber":"091-749-4674",
                    "uid":"0x4"
                 }
              },
              {
                 "entity":{
                    "auxId":"rec-00000000-bbb-0",
                    "city":"Nairobi",
                    "dob":"20171114",
                    "familyName":"Onyango",
                    "gender":"male",
                    "givenName":"Endalekachew",
                    "nationalId":"198804042874913",
                    "phoneNumber":"091-749-4674",
                    "uid":"0x6"
                 }
              }
           ]
        }
     ],
     "pagination":{
        "total": 100
     }
  }
}
