name: Build and Push JeMPI image

on:
  push:
    tags:
      - "*.*.*"
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push tag
        if: ${{ github.ref_name != 'main' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jembi/jempi-web:${{ github.ref_name }}

      - name: Build and push latest
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jembi/jempi-web:latest
