name: JeMPI Web Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-front-end:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Install yarn dependencies and test
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test
